config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "credit_cards#index"

  # Standard CRUD routes
  # get "/credit_cards", to: "credit_cards#index"
  # get "/credit_cards/:id", to: "credit_cards#show"

  # get "/credit_cards/new", to: "credit_cards#new"
  # post "/credit_cards", to: "credit_cards#create"

  # get "/credit_cards/:id/edit", to: "credit_cards#edit"
  # patch "credit_cards/:id", to: "credit_cards#update"
  # put "credit_cards/:id", to: "credit_cards#update"

  # delete "credit_cards/:id", to: "credit_cards#destroy"
  resources :credit_cards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  validates :name, presence: true
  validates :annual_fee, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :acquired_on, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @credit_cards = CreditCard.all
  end

  def show
  end

  def new
    @credit_card = CreditCard.new
  end

  def create
    @credit_card = CreditCard.new(credit_card_params)
    if @credit_card.save
      redirect_to @credit_card
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @credit_card.update(credit_card_params)
      redirect_to @credit_card
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @credit_card.destroy
    redirect_to credit_cards_path
  end

  private
    def set_product
      @credit_card = CreditCard.find(params[:id])
    end

    def credit_card_params
      params.expect(credit_card: [ :name, :annual_fee, :tags, :acquired_on ])
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_with model: credit_card do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :annual_fee %>
    <%= form.number_field :annual_fee %>
  </div>
  <div>
    <%= form.label :tags %>
    <%= form.text_field :tags, value: credit_card.tags %>
  </div>
  <div>
    <%= form.label :acquired_on %>
    <%= form.date_field :acquired_on, value: credit_card.acquired_on || Date.today %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Edit card</h1>

<%= render "form", credit_card: @credit_card %>
<%= link_to "Cancel", @credit_card %>

app/views/credit_cards/index.html.erb
<h1>Credit Cards</h1>

<%= link_to "+ Add card", new_credit_card_path, class: "btn" %>

<div id="credit-cards">
  <% @credit_cards.each do |card| %>
    <div>
      <%= link_to card.name, card %>
    </div>
  <% end %>
</div>

app/views/credit_cards/new.html.erb
<h1>New card</h1>

<%= render "form", credit_card: @credit_card %>
<%= link_to "Cancel", credit_cards_path %>

app/views/credit_cards/show.html.erb
<p><%= link_to "Back", credit_cards_path %></p>
<h1><%= @credit_card.name %></h1>
<p>Acquired on: <%= @credit_card.acquired_on %></p>
<p>Annual fee: <%= number_to_currency(@credit_card.annual_fee, unit: "$") if @credit_card.annual_fee %></p>
<p><%= @credit_card.tags %></p>


<section class="card">
  <%= link_to "Edit", edit_credit_card_path %>
  <%= button_to "Delete", @credit_card, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
  <%# link_to "Destroy", credit_card_path(@credit_card), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cardvault" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="container">
      <h1>Card Vault</h1>
      <nav>
        <%= link_to "Home", root_path %>
        <a href="#">Timeline</a>
        <a href="#">Explore</a>
        <a href="#">Account</a>
        <% if authenticated? %>
          <%= button_to "Log out", session_path, method: :delete %>
        <% else %>
          <%= button_to "Log in", new_session_path %>
        <% end %>
      </nav>
      <ul>
        Links
      </ul>
    </header>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>